### ISSUE TITLE
Please Update For Gimp 2.8.18

### ISSUE THREAD

**Issue by Geyup** [jabiertxof/gimpToSVG#1]
Hello,

Can you please update this for gimp 2.8.18?

I'm running Slackware 14.2 x86_64 with gimp 2.8.18 and the plugins don't work, I get this from the terminal;

Traceback (most recent call last):
  File "/home/foo/.gimp-2.8/plug-ins/pango_to_svg.py", line 9, in <module>
    import lxml.etree as etree
ImportError: No module named lxml.etree

(gimp:6564): LibGimpBase-WARNING **: gimp: gimp_wire_read(): error
Traceback (most recent call last):
  File "/home/foo/.gimp-2.8/plug-ins/gimp_export_as_svg.py", line 16, in <module>
    from lxml import etree
ImportError: No module named lxml

(gimp:6564): LibGimpBase-WARNING **: gimp: gimp_wire_read(): error

Slackware has libxml2-2.9.4, libxslt-1.1.29 and python 2.7.11

**Comment by jabiertxof** [comment]
you have instaled python-lxml? Its required

**Comment by Geyup** [comment]
WOW fast reply!

Oh don't have to thank me on the readme LOL...

I'll give it a try and report back...

thanks

**Comment by jabiertxof** [comment]
You are welcome!

**Comment by Geyup** [comment]
Ok I installed python-lxml and the requirements found here;

https://slackbuilds.org/repository/14.2/python/lxml/

I now see an entry in the menu File > Export as SVG, when I export it I see two files;

_Untitled_-task-attempt_svg.png
_task-attempt___imported_.svg

When I first started gimp I got this warning at the terminal;

(gimp:5862): LibGimpBase-WARNING **: gimp: gimp_wire_read(): error

To begin with, these names need some changing, removing the underscores and just having these called as example;

task.svg.png
imported.svg

No need for the word 'attempt'...

Now when I look at the _task-attempt___imported_.svg on my destop it's blank and if I click it to view in an image viewer I see nothing, but I can see it in Gimp.

Here's a screen shot of two of the images side by side the png and svg, you'll notice there's nothing to see for the svg;

http://i.imgur.com/D1s2oZg.jpg

Here's a screen shot when I clicked on the svg to view in an image viewer;

http://i.imgur.com/Cuvos7p.jpg

**Comment by jabiertxof** [comment]
please can you provide the original XCF?

**Comment by jabiertxof** [comment]
@Geyup  I rewrite the code, now basicaly a XCF gimp export each image layes as diferent PNG called "imagename"-"layername".".png". 
> If your XCF is fresh and not saved in the system "imagename" become "[Untitled]" and there is some substitution for special chars -like [...-.

Finaly if you save your image as "greatpic.xcf" with 2 layers ("Background","Layer2") you get 3 files in the output dir:
- greatpic.xcf.svg
- greatpic.xcf-Background.png
- greatpic.xcf-Layer2

**Comment by jabiertxof** [comment]
@Geyup the proyect name has changed to https://github.com/jabiertxof/GimpToSVG

**Comment by Geyup** [comment]
I placed the new three files in ~/.gimp-2.8/plug-ins then when I ran gimp for the first time with these 3 new files I saw this at the terminal, so not sure if problem or not;

Removing duplicate PDB procedure 'python-fu-export-as-svg' registered by '/home/foo/.gimp-2.8/plug-ins/gimp_export_as_svg.py'

And then after I start gimp I now end up with 5 files;

 ~/.gimp-2.8/plug-ins >ls
gimp_batch_export_as_svg.py  
gimp_export_as_svg.pyc  
pango_to_svg.pyc
gimp_export_as_svg.py
pango_to_svg.py

So now I open an SVG, make some ghanges to it, then I click File > SVG > Export As SVG.

Now the file name looks like this;

%5Btask-attempt%5D%20%28imported%29.svg

Also I can't see the image in a file manager, or imageviewer as before, I can only see it in gimp or inkscape, so we still have the same problems as before...

**Comment by jabiertxof** [comment]
> Removing duplicate PDB procedure 'python-fu-export-as-svg' registered by '/home/foo/.gimp-2.8/plug-ins/gimp_export_as_svg.py'

Is a know issue, I'm looking to it but it don't broke anything.
> Now the file name looks like this;

This is normal, the file names are url encoded to use in web. If you want more clean, don't use spaces or special chars 

By the way, is a problem to you start another Issue and close this. Now we are in other thing diferent to main issue. Thanks!

**Comment by jabiertxof** [comment]
@Geyup 
I just added url encode filenames as a optional value. So no more problems with filenames I hope.

**Comment by Geyup** [comment]
I don't understand what you mean about an SVG for usage with the WEB?

In Inkscape when saving as a ```.svg``` you only have three .svg options;

Inkscape SVG (*.svg)
Plain SVG (*.svg)
Optimized SVG (*.svg)

Neither of these options changes the name of the file like your plugin.

I'm assuming for the GIMP plugin, since there is only one option, that this only saves as a Inkscape SVG;

File > SVG > Export as SVG

**Comment by jabiertxof** [comment]
Hi @Geyup 
> In Inkscape I do not see any such web options, only saving as .html

SVG is a webformat itself, like the linked images
> I don't understand what you mean about an SVG for usage with the WEB?

If you link a image file with some special char in the name this not show always correctly in web,
> Neither of these options changes the name of the file like your plugin.

But if you name incorrectly the file coulden't be used in web. I want also give the user free to name the layers wath they want, not force url safe names.
> I'm assuming for the GIMP plugin, since there is only one option, that this only saves as a Inkscape SVG;

Realy save as **gimpToSVG** SVG, but this is redundant :). Anyway you could add options with inkscape attributes, but I not call it "Save as Inkscape SVG"

> I forgot to ask, what version of Python is required for the scripts?

I think 2.7 is good not have time to test with lower ones. I think not work with 3.x

**Comment by Geyup** [comment]
@jabiertxof thanks for your time and work here, much appreciated!

For now I'm not going to be able to continue helping, maybe later I'll be able to come back, but not sure.

Hopefully the little I've reported has been a help and maybe someone else with Slackware will be able to pick up for you.

Thanks again...

**Comment by jabiertxof** [comment]
#Geyup You are welcome. Sure your help a lot, and the extension is now too much powerful than later. 
Thanks to you!
I close the bug.
