### ISSUE TITLE
How to pass which parameters on the command line - expects 11 but received 2

### ISSUE THREAD

**Issue by HaakonME** [jabiertxof/gimpToSVG#2]
Hello, I have a number of raster images I want to batch convert to SVG, and I wanted to try your script. It worked nicely in the GUI, so I wanted to try it on the command line to include it in a script.

I started with

gimp -i -b '(python-fu-export-as-svg RUN-NONINTERACTIVE "/home/haakon/src/BK_logo.png")' -b '(gimp-quit 0)'

but I got

(gimp:10876): LibGimpBase-WARNING **: gimp: gimp_wire_read(): error
batch command experienced an execution error:
Error: (<unknown> : 145338396) Invalid number of arguments for python-fu-export-as-svg (expected 11 but received 2)

I assume I am supposed to add more parameters in "some parameter" as with the source image above, and I was hoping you can help me with which parameters I need to pass.

Cheers,
Haakon

**Comment by HaakonME** [comment]
I seem to have gotten a bit further with the parametres, but I am missing something. The string parameter seems to be the output path? Does it run on all images in the current directory, or do I need to indicate type of images I want it to look for?

gimp -i -b '(python-fu-export-as-svg RUN-INTERACTIVE 0 0 "/home/haakon/src/" 0 0 0 0 1 1 1)' -b '(gimp-quit 0)'

**Comment by jabiertxof** [comment]
I Just made a commit to remove a unused parameter.
current parameters are in:
https://github.com/jabiertxof/Gimp-to-SVG/blob/master/gimp_export_as_svg.py#L134
Required:
img: image name
path: path of image
Optionals:
only_visible: not export invisible layers
flatten: not made layers
remove_offsets:remove offsets,
crop: each image to data only,
inkscape_layers: add inkscape layers -a group with custom inkscape attribute
text_layers: Layers as text
resolution_96:96 DPI current svg DPI. False 90 DPI legacy SVG DPI:

**Comment by jabiertxof** [comment]
Currently I coulden`t get it working in my machine in GUI mode or is a gimp update but not show the menu, need more time to get into. Not sure if last commit can break things, if break something take previous version and add a NULL extra parameter after img : null

**Comment by HaakonME** [comment]
img: does it refer to input name? E.g. if I have a file named "logo.png" I want exported as SVG I put in "logo.png" here?
path: does it refer to input path? E.g. if the above file is in "/home/haakon/images/" then I need to supply the path to where the image I want to convert is?

Or is it the other way round? img and path refers to output name and output path?

**Comment by jabiertxof** [comment]
@HaakonME  I just update my previous comments.
Image is the source with path
Path is the destination folder

**Comment by jabiertxof** [comment]
Not sure about the parameter removed in last commit, any gimp expert maybe can help about. Maybe I add it again in the future.

**Comment by HaakonME** [comment]
Great, can the image source be a path do a directory?

**Comment by jabiertxof** [comment]
I think you need full path+img name but never use from command line. maybe can use current location relative paths. Can you try it?

**Comment by HaakonME** [comment]
Hm. I pulled the latest and copied it into the plugins folder - it is executable.

gimp -i -b '(python-fu-export-as-svg RUN-NONINTERACTIVE "/home/haakon/src/gif2svg/BK_logo.png" "/home/haakon/src/gif2svg/" 0 0 0 0 1 1 1)' -b '(gimp-quit 0)'

and the result is

(gimp:11758): LibGimpBase-WARNING **: gimp: gimp_wire_read(): error
batch command experienced an execution error:
Error: (<unknown> : 158670918) Invalid type for argument 2 to python-fu-export-as-svg

**Comment by jabiertxof** [comment]
The script is to use GIMP files not PNG. It convert a gimp with layers, text... to a SVG.

**Comment by HaakonME** [comment]
Aha! I will look into it.

**Comment by HaakonME** [comment]
I opened the PNG in GIMP and saved it as a XCF, then tried two times
 gimp -i -b '(python-fu-export-as-svg RUN-NONINTERACTIVE "/home/haakon/src/gif2svg/BK_logo.xcf" "/home/haakon/src/gif2svg/" 0 0 0 0 1 1 1)' -b '(gimp-quit 0)'

(gimp:11849): LibGimpBase-WARNING **: gimp: gimp_wire_read(): error
batch command experienced an execution error:
Error: (<unknown> : 161521734) Invalid type for argument 2 to python-fu-export-as-svg 

gimp -i -b '(python-fu-export-as-svg RUN-NONINTERACTIVE "BK_logo.xcf" "/home/haakon/src/gif2svg/" 0 0 0 0 1 1 1)' -b '(gimp-quit 0)'

(gimp:11854): LibGimpBase-WARNING **: gimp: gimp_wire_read(): error
batch command experienced an execution error:
Error: (<unknown> : 159109165) Invalid type for argument 2 to python-fu-export-as-svg

**Comment by jabiertxof** [comment]
Hi @HaakonME  searching to your problem:
The argument 2 is a img object you can't call it with the file directly you need to use with something like "file_xmc_load" from command line: file_xmc_load(RUN-NONINTERACTIVE,filename, raw_filename).
maybe you can use the same -file_XXX_load- for other extensions, not sure, but I think yes.

**Comment by jabiertxof** [comment]
Hi again @HaakonME  I just commit a new code with a export in batch. Also in readme.md there is a example of usage in comand line.

**Comment by jabiertxof** [comment]
Also added suport to gif, jpeg, png,tiff and bmp.

**Comment by HaakonME** [comment]
Brilliant! Thank you, Jabiertxo! :+1:

**Comment by jabiertxof** [comment]
@HaakonME I do a lot of improvements and also change proyect name to https://github.com/jabiertxof/GimpToSVG. plaase recheck.

**Comment by HaakonME** [comment]
Nice work, Jabiert. +1 

The command line seems to be

gimp -i -b '(python-fu-batch-export-as-svg RUN-NONINTERACTIVE "/path/to/input/directory" "/path/to/output/directory" 0 0 0 0 1 1 1)' -b '(gimp-quit 0)'

and the optional options are required arguments and the input and output directory cannot be the same directory.

Some small improvements to polish things
1) The output filename is the original filename including the extension appended with .svg. This means filename.png becomes filename.png.svg . It would be better to just have filename.svg as the output, which is probably the common use case. 

There may be the case where you have the same file in different input formats, e.g. filename.gif , filename.png , and you want to compare which gave the best output, either filename.gif.svg or filename.png.svg, but I doubt it is common, and it could perhaps be a boolean option?

2) To the output directory there is written a copy of the original input file as well as the converted SVG. It would be better to just write the SVG.

3) If the input directory contains files that are not amongst the allowed formats, the batch job terminates with an error message, rather than skipping those files - perhaps the Python-Fu samples batch scripts below contain some helpful tips? 

4) There is a warning issued every time the batch is run - see below. 

gimp --verbose -i -b '(python-fu-batch-export-as-svg RUN-NONINTERACTIVE "/home/haakon/inputdirectory" "/home/haakon/outputdirectory" 0 0 0 0 1 1 1)' -b '(gimp-quit 0)'
INIT: gimp_load_config
Parsing '/home/haakon/.gimp-2.8/unitrc'
Parsing '/etc/gimp/2.0/gimprc'
Parsing '/home/haakon/.gimp-2.8/gimprc'
gimp_composite: verbose=no
Processor instruction sets: +mmx +sse +sse2 -3dnow -altivec -vis
INIT: gimp_initialize
INIT: gimp_real_initialize
INIT: gimp_restore
Parsing '/home/haakon/.gimp-2.8/parasiterc'
Loading 'brush factory' data
Loading 'dynamics factory' data
Loading 'pattern factory' data
Loading 'palette factory' data
Loading 'gradient factory' data
Loading fonts
Parsing '/home/haakon/.gimp-2.8/templaterc'
INIT: gimp_real_restore
Parsing '/home/haakon/.gimp-2.8/pluginrc'
Querying plug-in: '/home/haakon/.gimp-2.8/plug-ins/pango_to_svg.py'

(gimp:13572): LibGimpBase-WARNING **: gimp: gimp_wire_read(): error
Terminating plug-in: '/home/haakon/.gimp-2.8/plug-ins/pango_to_svg.py'
Querying plug-in: '/home/haakon/.gimp-2.8/plug-ins/gimp_export_as_svg.py'
Removing duplicate PDB procedure 'python-fu-export-as-svg' registered by '/home/haakon/.gimp-2.8/plug-ins/gimp_export_as_svg.py'
Writing '/home/haakon/.gimp-2.8/pluginrc'
Starting extension: 'extension-script-fu'
Ingen mengdetolker er valgt, bruker forvalgt «plug-in-script-fu-eval».
batch command executed successfully
EXIT: gimp_exit
EXIT: gimp_real_exit
Terminating plug-in: '/usr/lib/gimp/2.0/plug-ins/script-fu'
Terminating plug-in: '/usr/lib/gimp/2.0/plug-ins/script-fu'
Writing '/home/haakon/.gimp-2.8/templaterc'
Writing '/home/haakon/.gimp-2.8/parasiterc'
Writing '/home/haakon/.gimp-2.8/unitrc'
EXIT: app_exit_after_callback

I found two resources that might be helpful resolving the warning
http://www.gimptalk.com/index.php?/topic/50502-plug-in-works-in-gimp-but-problem-in-batch/
http://registry.gimp.org/node/28124 - Python-Fu samples with two batch scripts.

Thank you again for all your effort! :+1:

**Comment by jabiertxof** [comment]
```
1) The output filename is the original filename including the extension appended with .svg. This means filename.png becomes filename.png.svg . It would be better to just have filename.svg as the output, which is probably the common use case. 
```
I think is better have a reference to original file name intact, I dont want add more optionals but maybe in the future add it :)
```
2) To the output directory there is written a copy of the original input file as well as the converted SVG. It would be better to just write the SVG.
```
Realy not agree, I want the resulting SVG need be easy moved, by this way I need to recreate folders structures.
```
3) If the input directory contains files that are not amongst the allowed formats, the batch job terminates with an error message, rather than skipping those files - perhaps the Python-Fu samples batch scripts below contain some helpful tips? 
```
It not happends to me. Could you send me more info?
```
4) There is a warning issued every time the batch is run - see below. 
```

Fixed

**Comment by HaakonME** [comment]
Thanks again, Jabiert! +1

I do not think I understand your description of 1) and 2), so let me see if I can get it by an example.

Here we have three files in an input directory and an additional three files in a subdirectory of the input directory

/path/to/input/directory/filename_001.png
/path/to/input/directory/filename_002.png
/path/to/input/directory/filename_003.png
/path/to/input/directory/subdirectory/filename_004.png
/path/to/input/directory/subdirectory/filename_005.png
/path/to/input/directory/subdirectory/filename_006.png

If the script supports recursively moving into subdirectories, then given the current naming and file duplication we should get the following in the output directory and its autocreated subdirectory.

/path/to/output/directory/filename_001.png
/path/to/output/directory/filename_001.png.svg
/path/to/output/directory/filename_002.png
/path/to/output/directory/filename_002.png.svg
/path/to/output/directory/filename_003.png
/path/to/output/directory/filename_003.png.svg
/path/to/output/directory/subdirectory/filename_004.png
/path/to/output/directory/subdirectory/filename_004.png.svg
/path/to/output/directory/subdirectory/filename_005.png
/path/to/output/directory/subdirectory/filename_005.png.svg
/path/to/output/directory/subdirectory/filename_006.png
/path/to/output/directory/subdirectory/filename_006.png.svg

while what I suggested would result in

/path/to/output/directory/filename_001.svg
/path/to/output/directory/filename_002.svg
/path/to/output/directory/filename_003.svg
/path/to/output/directory/subdirectory/filename_004.svg
/path/to/output/directory/subdirectory/filename_005.svg
/path/to/output/directory/subdirectory/filename_006.svg

which leaves the originals intact in the input directory, and the content of the output directory looks to me like it would be very easy to move or create an archive file with only the outputted SVG files, e.g. a ZIP-file, but perhaps you have another use case in mind?

**Comment by jabiertxof** [comment]
@HaakonME 
- **First comment**: Im not sure about it, maybe implement it but not sure 
- **Second comment**: I don't want to use absolute paths in my script output!

**Comment by HaakonME** [comment]
This is an update to 3) which caused the script to crash. This is an interesting one. As it turned out, I had a folder with 706 files with a GIF extension. However, upon closer inspection with identify from imagemagick, it turned out some of these where really two other formats. Below is a snippet

identify *.gif
...
wizardlogo1577.gif[699] GIF 33x40 33x40+0+0 8-bit sRGB 256c 2.12KB 0.000u 0:00.000
wizardlogo1578.gif[700] JPEG 166x62 166x62+0+0 8-bit CMYK 590KB 0.010u 0:00.000
wizardlogo1580.gif[701] PNG 25x32 25x32+0+0 8-bit sRGB 4.41KB 0.000u 0:00.000
...

I do not know how these files came to have the wrong extension, I just received them all in ZIP-file.

identify *.gif|grep -v GIF | wc -l

gave the total answer 72, 39 PNGs and 33 JPEG.

It might be safer - if possible - if the script can correctly identify the format inside the file without relying on the file extension. In fact, https://docs.gimp.org/en/gimp-using-fileformats-opening.html says GIMP does this, looking for "magic headers" as it cannot rely on file extensions. Weird it does not do that when doing batch processes.

**Comment by HaakonME** [comment]
For now I converted those 72 files with BIMP to real GIF, ran this wonderful batch script, and then did

rename 's/\.gif//' *

in the output folder to rename the files from filename.gif.svg to filename.gif.

**Comment by jabiertxof** [comment]
Hi @HaakonME 
> Second comment: Not my intention to imply absolute paths, relative to invocation or whatever. +1

This is dificult because you can get the source from other paths, not always is the down folder

> For now I converted those 72 files with BIMP to real GIF, ran this wonderful batch script, and then did rename 's/.gif//' *

This is wrong, because you need to link correctly the images into the SVG, using sed for example.
Maybe I add a option you like soon to help you

> This is an update to 3) which caused the script to crash

It has a boring fix. I don,t want magic dependence. Anyway I put a comment in the readme.md to ensure users correct mimetypes in the process.

**Comment by jabiertxof** [comment]
Hi @HaakonME 
In last commit I just add a option to remove original extension.
Cheers, Jabier.

**Comment by jabiertxof** [comment]
I just add a option to embed the images inside the SVG.
