### ISSUE TITLE
Some phrasing problems in the project's description

### ISSUE THREAD

**Issue by shlomif** [jabiertxof/gimpToSVG#4]
The description reads «Gimp plug-in for export layers to SVG». It should be “GIMP plugin for exporting ["all the"?] layers to SVG". Please correct it.

**Comment by jabiertxof** [comment]
Changed. Thanks!

**Comment by shlomif** [comment]
Thanks @jabiertxof ! That put aside, you've introduced a new issue - “GIMP plugin for exporting all layers to SVG and batch export [should be "exporting"] images to SVGs”.

**Comment by jabiertxof** [comment]
Fixed, Thanks!

**Comment by jabiertxof** [comment]
Close the bug. Thanks @shlomif !

**Comment by shlomif** [comment]
Thanks @jabiertxof and you're welcome.
