### ISSUE TITLE
Saved SVG Creates Blank Image...

### ISSUE THREAD

**Issue by Geyup** [jabiertxof/gimpToSVG#5]
When I save the image to SVG, the image does not appear in file managers, or an image viewer.

I tested this with 3 file managers and the .svg didn't appear in any of them;

SpaceFM - 1.0.4
Thunar - 1.6.10
PCManFM - 1.2.3

I did not see the image in either of these image viewers;

gpicview-0.2.5
feh - 2.17

Here's a screen shot of the saved images side by side, the png and svg, you'll notice there's nothing to see for the svg;

http://i.imgur.com/D1s2oZg.jpg

Here's a screen shot when I clicked on the svg to view in gpicview;

http://i.imgur.com/Cuvos7p.jpg

**Comment by jabiertxof** [comment]
Please provide original files

**Comment by jabiertxof** [comment]
And output files

**Comment by jabiertxof** [comment]
Hi @Geyup 
First of all can you:
- Open your favourite SVG editor
- Insert a image in the middle of the document. The image need to be linked not embed
- Save the SVG
- Try to see in the programs you tell

As far as I know is usual file explorers don't show previews of SVG files.
Also your pic viewers maybe don't support linked images or SVG.

**Comment by jabiertxof** [comment]
I also just add a option to embed images instead linking it.

**Comment by Geyup** [comment]
See #1 

Thanks

**Comment by jabiertxof** [comment]
Close it as invalid @Geyup and anyone feel free to open when you want.
